version: '3'

tasks:
  run:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - ./venv/bin/python3 src/main.py

  api:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - ./venv/bin/uvicorn src.api:app --reload --host 0.0.0.0 --port 8000

  install:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - rm -rf venv
      - python3 -m venv venv
      - ./venv/bin/python3 -m pip install -r requirements.txt