version: '3'

tasks:
  native:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - MOD=native ./venv/bin/python3 -m src.main

  api:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - MOD=api ./venv/bin/python3 -m src.main

  install:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - rm -rf venv
      - python3 -m venv venv
      - ./venv/bin/python3 -m pip install -r requirements.txt
